### ISSUE TITLE
"Takeoff Go-Around" filter in non-time series data

### ISSUE THREAD

**Issue by BFNestico** [ge-flight-analytics/ems-api-sdk#11]
In the EMS Explorer, for a specific time series record it will determine when various "phases of flight" occur.  Are the tools capable of identifying if a Takeoff Go-Around occurs and can it be used as a filter when searching non-time series data?

**Comment by richardpineo** [comment]
Yes, there are a couple of ways to implement this. The most straightforward way is to query for the 'Takeoff Go-Around' event and retrieve the flight records from that. I'm not sure what a 'takeoff go-around' is though... I know what a go around is on landing and what a rejected takeoff is. 
Anyway, to query for this, locate the event of interest in the 'databases tree' and use that as the 'database id' in a new query. The selected fields could include the flight record number and anything else of interest.

These images show how to locate the 'go around' for the flight safety events profile.
![screen shot 2017-06-13 at 10 05 43 am](https://user-images.githubusercontent.com/8593979/27094771-119f713e-5020-11e7-9824-91eb102ec411.png)
![screen shot 2017-06-13 at 10 06 18 am](https://user-images.githubusercontent.com/8593979/27094770-1194022c-5020-11e7-9153-5d1d29f06a45.png)

**Comment by KMoon01** [comment]
One thing I can think of is that you can create a custom profile with
measurements that returns specific time points that you are interested in
such as start/end timepoints of takeoff and/or go-around. Those time points
can be found from any of the standard library profiles.

Then you can load the custom profile and query the those start/end
timepoints in Python, and query time series filtered by those time
intervals for individual flights.
