### ISSUE TITLE
Phase start/end times in Flight Record Query?

### ISSUE THREAD

**Issue by BFNestico** [ge-flight-analytics/ems-api-sdk#12]
Is anybody aware of if the following start/end times are available to a Flight Record query?  For example, if I would like to download just the takeoff phase of the CEOD file, I am currently performing two TS queries, (1) retrieves first couple of entries just to identify the start/end times and (2) a second query using the start/end times gathered from the first query.  

		"Start of the First Occurrence of A) Start & Push",
		"End of the Last Occurrence of A) Start & Push",
		"Start of the First Occurrence of B) Taxi Out",
		"End of the Last Occurrence of B) Taxi Out",
		"Start of the First Occurrence of C) Takeoff",
		"End of the Last Occurrence of C) Takeoff",
		"Start of the First Occurrence of F) Climb",
		"End of the Last Occurrence of F) Climb",
		"Start of the First Occurrence of G) Enrout",
		"End of the Last Occurrence of G) Enrout",
		"Start of the First Occurrence of H) Descent",
		"End of the Last Occurrence of H) Descent",
		"Start of the First Occurrence of I) Approach",
		"End of the Last Occurrence of I) Approach",
		"Start of the First Occurrence of M) Taxi in",
		"End of the Last Occurrence of M) Taxi in"

**Comment by richardpineo** [comment]
Brian - at this time, there isn't a way to retrieve offsets in a flight and the time-series in a single AJAX call via the API. Instead, you'll need to execute two requests - one to get the desired locations in the data and a second to retrieve the data for those locations as you mention in your problem statement.

This is a request we've heard from another client and so we'll definitely add your use case to the user story to try to prioritize it in our queue. 

The general case here is to create an API that allows the user to specify a start and end timepoint for a flight or set of flights and retrieves time-series data for that range for the specified flights. For reference, this is US78823.
