### ISSUE TITLE
Request: CEFA Exports via API

### ISSUE THREAD

**Issue by soho737** [ge-flight-analytics/ems-api-sdk#17]
Hi Cody,
any chance you could provide us with an API endpoint to export a flight into the CEFA format for visualization?

Thanks,
Karsten

**Comment by KenKozman-GE** [comment]
Great suggestion Karsten (one which has come up before). I will add an idea for this in our Aha portal.

One follow up: would the use case you are thinking about be better served by automated exports via the EDC framework?

**Comment by soho737** [comment]
Hi Ken,
thanks for picking this up.

The use case wouldn't actually be better served via EDC as I'd like to have a pretty small tray application on our Visualization Server where a user hacks in a Flight Record Number and some time stamps  for beginning and end - and the CEFA file magically appears on their desktop :)

**Comment by KenKozman-GE** [comment]
Got it. That is a cool use case, thanks Karsten.

I'm going to close this here as it is more of an API feature and thus captured in Aha. Versus exposing an existing API through our language wrappers, which will be part of that work.
