### ISSUE TITLE
selecting all params in emspy

### ISSUE THREAD

**Issue by BFNestico** [ge-flight-analytics/ems-api-sdk#9]
Is anybody aware of a way to pull all the available params from a non-time series based query using emspy?  (Rather than specifying all of them with the select function)

Brian

**Comment by richardpineo** [comment]
Brian - 
Could you describe more about what you want to do here? The reason why is that there are literally tens of thousands of columns that are available in a query and so retrieving all of them probably isn't what you are looking for.
-Richard

**Comment by KMoon01** [comment]
Brian,

I never meant to design this way, but there is a trick that is close to
what you want to do.

When you call a select method from FltQuery, if you feed an empty string
which is "" and set "unique = False", the select method actually returns
with all measurement in your metadata. Examples are:

# Return all measurments in the meta data
fq.select("", unique=False)

# Return all measurements in the meta data that are under "Flight
Information" folder
fq.select( ("flight info", ""), unique=False)

# Return all measurements under Navigation Information / Takeoff / all
children folders / all measurements under those children folders
fq.select( ("navigation info", "takeoff", "", ""), unique=False)

Is it something that you look for??

By the way, I realized that this was only working at my local branch so just update so in the remote origin. Please update your git repo and use either v0.2 or mult-proc branch to make this work.

-KJ

**Comment by BFNestico** [comment]
KJ & Richard,
I can see there being value in knowing all the available parameters in a searchable list (similar to a data dictionary).  This is especially true when there are multiple parameters with the same name but under different parent folders.  In other cases, a user doesn't know what they don't know and having a complete list of what is available can be informative.  

For the recent 737MAX/LEAP1B service data, I have noticed some unexpected values for a few of the parameters.  Specifically, I am wondering if I an correctly requesting the appropriate parameter name, along with parent and child folders. 

I downloaded the latest multi-proc branch version and was unsuccessful in getting the "empty select string" approach to return a result.

Regards,
Brian

**Comment by KMoon01** [comment]
It's strange because I have been using it... Did you set "unique=False" to
the select function?

**Comment by KMoon01** [comment]
By the way, if you just meant to see all the measurement names, you can just use the trick that we once talked about. One of them is to look into your meta-data file using LocalData class. You basically get the Pandas dataframe of the all measurements info in the meta-data so you can print or search for measurements.

**Comment by BFNestico** [comment]
If I use the following code, I am table to get a solid search capability on the non-time series data….

meta_data = LocalData(".//emspy//data//emsMetaData.db")
parms_df = meta_data.get_data("fieldtree")
parms_df[parms_df.name.str.contains("aircraft", case = False)]


If I find a parameter of interest, what is the proper way to call out the id + tree structure in the select function given the following info…..

>>> parms_df.iloc[28]
ems_id                                                       1
db_id                    [ems-core][entity-type][foqa-flights]
id           [-hub-][field][[[ems-core][entity-type][foqa-f...
nodetype                                                 field
type                                                  discrete
name                                     Aircraft Registration
parent_id    [-hub-][field-group][[[ems-core][entity-type][...
Name: 28, dtype: object


>>> parms_df['id'].loc[28]
u'[-hub-][field][[[ems-core][entity-type][foqa-flights]][[ems-core][base-field][flight.aircraft-version]]]'
>>> parms_df['parent_id'].loc[28]
u'[-hub-][field-group][[[ems-core][entity-type][foqa-flights]][[ems-core][internal-field-group][aircraft-info]]]'


Is this the correct way to declare the parameter based on the “parent_id” info?
query.select(("aircraft info","Aircraft Registration") )

**Comment by KMoon01** [comment]
Hello Brian,

This may do:
```python
p_id = parms_df[parms_df.name.str.contains("aircraft info", case = False) &
parms.nodetype=="field_group"]["id"]

# Assuming p_id is a single value
my_fields = parms_df[parms_df.parent_id == p_id]['name']

# Select
query.select(*my_fields)
```

However, I am still unsure why the "empty string" trick doesn't work work
for you...This would have been an easy solution if it works. Can you
double-check the following:

- Did you restart the Python kernel after updating your local git repo?
- If you manage the local copy with the Git program, did you change your
branch to the correct one (either mult-proc, v0.2, or master)?

 Thanks,

-KJ
